version: 2
jobs:
  build:
    working_directory: /docker-laravel-app
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install docker compose
          command: |
            apt-get update
            apt-get install -y docker-compose==1.15.0
      - run:
          name: Run docker compose
          command: docker-compose up -d